# Generated by Django 3.2.18 on 2023-04-16 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_phone', models.CharField(max_length=20)),
                ('supplier_address', models.CharField(max_length=200)),
                ('tax_increase', models.FloatField()),
                ('tax_decrease', models.FloatField()),
                ('transportation_cost', models.FloatField()),
                ('total_invoice_cost', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('remaining_balance', models.FloatField()),
                ('invoice_image', models.ImageField(upload_to='invoice_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=50)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_group', models.CharField(max_length=100)),
                ('asset_description', models.CharField(max_length=200)),
                ('asset_price', models.FloatField()),
                ('asset_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.assetinvoice')),
            ],
        ),
    ]
