# Generated by Django 4.2.1 on 2023-05-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=50, verbose_name='اسم الاصل')),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_group', models.CharField(max_length=100)),
                ('asset_description', models.CharField(max_length=200)),
                ('asset_price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_images/'),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='remaining_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='supplier_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='supplier_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='tax_decrease',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='tax_increase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='total_invoice_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='transportation_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.AddField(
            model_name='assetitems',
            name='invoice_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.assetinvoice'),
        ),
    ]
