# Generated by Django 4.2.1 on 2023-05-06 16:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0002_assetitems_alter_assetinvoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinvoice',
            name='invoice_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='assetitems',
            name='asset_description',
            field=models.CharField(max_length=200, verbose_name='البيان'),
        ),
        migrations.AlterField(
            model_name='assetitems',
            name='asset_group',
            field=models.CharField(max_length=100, verbose_name='مجموعة الاصل'),
        ),
        migrations.AlterField(
            model_name='assetitems',
            name='asset_name',
            field=models.CharField(max_length=100, verbose_name='اسم الاصل'),
        ),
        migrations.AlterField(
            model_name='assetitems',
            name='asset_number',
            field=models.CharField(max_length=50, verbose_name='رقم الاصل'),
        ),
        migrations.AlterField(
            model_name='assetitems',
            name='asset_price',
            field=models.FloatField(verbose_name='سعر الاصل'),
        ),
        migrations.AlterField(
            model_name='assetitems',
            name='invoice_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.assetinvoice', verbose_name='رقم الفاتورة'),
        ),
    ]
