# Generated by Django 4.2 on 2023-05-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0006_additiontax_discounttax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinvoice',
            name='tax_increase',
            field=models.FloatField(blank=True, null=True, verbose_name='ضريبة بالزيادة'),
        ),
    ]
