# Generated by Django 4.2 on 2023-05-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0008_alter_additiontax_percent_addition_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinvoice',
            name='addition_tax',
            field=models.CharField(choices=[('percent', 'percent'), ('value', 'value')], max_length=10, verbose_name='CHOIC'),
        ),
    ]
