# Generated by Django 4.2 on 2023-05-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0009_alter_assetinvoice_addition_tax'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountTax',
        ),
        migrations.AddField(
            model_name='additiontax',
            name='addition_type',
            field=models.CharField(choices=[('percent', 'نسبة'), ('value', 'قيمة')], default='percent', max_length=20, verbose_name='نوع الضريبة'),
        ),
        migrations.AddField(
            model_name='additiontax',
            name='choice_field_coast',
            field=models.CharField(choices=[('total_price', 'السعر بدون مصروفات'), ('total_invoice_cost', 'السعر شامل المصروفات')], default='total_invoice_cost', max_length=20, verbose_name='ربط الحقول'),
        ),
        migrations.AddField(
            model_name='assetinvoice',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='اجمالي الاسعار'),
        ),
        migrations.AlterField(
            model_name='additiontax',
            name='percent_addition_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='نسبة الضريبة'),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='addition_tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='add_asset_invoice.additiontax', verbose_name='ضريبة الزيادة'),
        ),
    ]
