# Generated by Django 4.2.1 on 2023-05-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0012_assetinvoice_discount_tax_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionTax',
            new_name='SystemAdditionTax',
        ),
        migrations.RenameModel(
            old_name='DiscountTax',
            new_name='SystemDiscountTax',
        ),
    ]
