# Generated by Django 4.2 on 2023-05-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0013_rename_additiontax_systemadditiontax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinvoice',
            name='addition_tax',
        ),
        migrations.RemoveField(
            model_name='assetinvoice',
            name='tax_increase',
        ),
        migrations.CreateModel(
            name='AdditionTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_tax_increase', models.FloatField(blank=True, null=True, verbose_name='قيمة ضريبة الاضافة')),
                ('addition_tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='add_asset_invoice.systemadditiontax', verbose_name='نظام ضريبة الاضافة')),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.assetinvoice', verbose_name='رقم الفاتورة')),
            ],
        ),
    ]
