# Generated by Django 4.2 on 2023-05-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0014_remove_assetinvoice_addition_tax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_expenses_cost', models.FloatField(blank=True, null=True, verbose_name='قيمة المصروف')),
            ],
        ),
        migrations.CreateModel(
            name='MinusTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_tax_decrease', models.FloatField(blank=True, null=True, verbose_name='قيمة ضريبة الخصم')),
            ],
        ),
        migrations.CreateModel(
            name='SystemExpensesCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_expenses_cost', models.CharField(max_length=100, verbose_name='اسم المصروف')),
            ],
        ),
        migrations.CreateModel(
            name='SystemMinusTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minus_tax', models.CharField(max_length=100, verbose_name='ضريبة الخصم')),
                ('minus_type', models.CharField(choices=[('percent', 'نسبة'), ('value', 'قيمة')], default='percent', max_length=20, verbose_name='نوع الضريبة')),
                ('choice_field_coast', models.CharField(choices=[('total_price', 'السعر بدون مصروفات'), ('total_invoice_cost', 'السعر شامل المصروفات')], default='total_invoice_cost', max_length=20, verbose_name='ربط الحقول')),
                ('percent_minus_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='نسبة الضريبة')),
                ('value_minus_tax', models.FloatField(blank=True, null=True, verbose_name='قيمة الضريبة')),
            ],
        ),
        migrations.RemoveField(
            model_name='assetinvoice',
            name='discount_tax',
        ),
        migrations.RemoveField(
            model_name='assetinvoice',
            name='tax_decrease',
        ),
        migrations.DeleteModel(
            name='SystemDiscountTax',
        ),
        migrations.AddField(
            model_name='minustax',
            name='invoice_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.assetinvoice', verbose_name='رقم الفاتورة'),
        ),
        migrations.AddField(
            model_name='minustax',
            name='minus_tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='add_asset_invoice.systemminustax', verbose_name='نظام ضريبة الخصم'),
        ),
        migrations.AddField(
            model_name='expensescost',
            name='expenses_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='add_asset_invoice.systemexpensescost', verbose_name='تكلفة المصروفات'),
        ),
        migrations.AddField(
            model_name='expensescost',
            name='invoice_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.assetinvoice', verbose_name='رقم الفاتورة'),
        ),
    ]
