# Generated by Django 4.2 on 2023-05-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0015_expensescost_minustax_systemexpensescost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinvoice',
            name='transportation_cost',
        ),
    ]
