# Generated by Django 4.2.1 on 2023-05-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0016_remove_assetinvoice_transportation_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinvoice',
            name='total_addition_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='اجمالي ضريبة الاضافة'),
        ),
        migrations.AddField(
            model_name='assetinvoice',
            name='total_expences_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='اجمالي المصروفات'),
        ),
        migrations.AddField(
            model_name='assetinvoice',
            name='total_minus_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='اجمالي ضريبة النقص'),
        ),
    ]
