# Generated by Django 4.2 on 2023-05-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0017_assetinvoice_total_addition_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetitems',
            name='count',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='عدد'),
        ),
        migrations.AddField(
            model_name='assetitems',
            name='price',
            field=models.FloatField(default=1, verbose_name='السعر'),
        ),
    ]
