# Generated by Django 4.2 on 2023-05-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0020_alter_assetitems_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetitems',
            name='count',
            field=models.FloatField(default=1, verbose_name='عدد'),
        ),
    ]
