# Generated by Django 4.2 on 2023-05-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0021_alter_assetitems_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100, verbose_name='الفرع')),
            ],
        ),
        migrations.AlterField(
            model_name='assetgroup',
            name='asset_group',
            field=models.CharField(max_length=100, verbose_name='تصنيف'),
        ),
        migrations.AlterField(
            model_name='assetitems',
            name='asset_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='add_asset_invoice.assetgroup', verbose_name='تصنيف'),
        ),
        migrations.AddField(
            model_name='assetinvoice',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='add_asset_invoice.branch', verbose_name='الفرع'),
        ),
    ]
