# Generated by Django 4.2 on 2023-05-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0022_branch_alter_assetgroup_asset_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetinvoice',
            old_name='branch',
            new_name='branch_name',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الفرع'),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الفرع'),
        ),
    ]
