# Generated by Django 4.2 on 2023-05-27 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0023_rename_branch_assetinvoice_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinvoice',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='add_asset_invoice.branch', verbose_name='الفرع'),
        ),
    ]
