# Generated by Django 4.2 on 2023-05-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0024_alter_assetinvoice_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinvoice',
            name='branch_name',
        ),
    ]
