# Generated by Django 4.2 on 2023-05-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0025_remove_assetinvoice_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_id',
        ),
    ]
