# Generated by Django 4.2 on 2023-05-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0026_remove_branch_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinvoice',
            name='branch_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='add_asset_invoice.branch', verbose_name='الفرع'),
        ),
    ]
