# Generated by Django 4.2 on 2023-05-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0027_assetinvoice_branch_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetinvoice',
            old_name='branch_name',
            new_name='branch',
        ),
    ]
