# Generated by Django 4.2 on 2023-05-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0028_rename_branch_name_assetinvoice_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinvoice',
            name='branch',
        ),
    ]
