# Generated by Django 4.2 on 2023-05-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0029_remove_assetinvoice_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinvoice',
            name='branch_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='add_asset_invoice.branch', verbose_name='الفرع'),
        ),
    ]
