# Generated by Django 4.2 on 2023-06-10 04:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0030_assetinvoice_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinvoice',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='add_asset_invoice.branch', verbose_name='الفرع'),
        ),
        migrations.CreateModel(
            name='Destruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destruction_start_month', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ بداية الاهلاك')),
                ('destruction_end_month', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاريخ مهاية الاهلاك')),
                ('destruction_percent', models.FloatField(blank=True, null=True, verbose_name='نسبة الاهلاك')),
                ('destruction_value', models.FloatField(blank=True, null=True, verbose_name='نسبة الاهلاك')),
                ('asset_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='add_asset_invoice.assetitems', verbose_name='رقم الاصل')),
            ],
        ),
    ]
