# Generated by Django 4.2 on 2023-06-24 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0031_alter_assetinvoice_branch_name_destruction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetitems',
            options={'ordering': ['invoice_number']},
        ),
        migrations.AlterField(
            model_name='destruction',
            name='destruction_end_month',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='نهاية الاهلاك'),
        ),
        migrations.AlterField(
            model_name='destruction',
            name='destruction_start_month',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='بداية الاهلاك'),
        ),
        migrations.AlterField(
            model_name='destruction',
            name='destruction_value',
            field=models.FloatField(blank=True, null=True, verbose_name='قيمة الاهلاك'),
        ),
    ]
