# Generated by Django 4.2 on 2023-06-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0033_rename_asset_number_destruction_asset_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destruction',
            old_name='asset_item',
            new_name='asset_number',
        ),
    ]
