# Generated by Django 4.2 on 2023-06-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0035_remove_destruction_asset_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetitems',
            name='destruction_percent',
            field=models.FloatField(default=1, verbose_name='نسبة الاهلاك'),
        ),
        migrations.AddField(
            model_name='assetitems',
            name='destruction_value',
            field=models.FloatField(default=1, verbose_name='قيمة الاهلاك'),
        ),
    ]
