# Generated by Django 4.2 on 2023-06-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0036_assetitems_destruction_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetitems',
            name='destruction_percent',
            field=models.FloatField(default=0.1, verbose_name='نسبة الاهلاك'),
        ),
    ]
