# Generated by Django 4.2 on 2023-06-28 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0037_alter_assetitems_destruction_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetitems',
            name='destruction_start_month',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='بداية الاهلاك'),
        ),
    ]
