# Generated by Django 4.2 on 2023-07-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0039_assetitems_destruction_end_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destruction',
            name='destruction_percent',
            field=models.FloatField(blank=True, verbose_name='نسبة الاهلاك'),
        ),
        migrations.AlterField(
            model_name='destruction',
            name='destruction_value',
            field=models.FloatField(blank=True, verbose_name='قيمة الاهلاك'),
        ),
    ]
