# Generated by Django 4.2 on 2023-07-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0041_alter_destruction_destruction_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destruction',
            name='destruction_percent',
            field=models.FloatField(verbose_name='نسبة الاهلاك'),
        ),
        migrations.AlterField(
            model_name='destruction',
            name='destruction_value',
            field=models.FloatField(verbose_name='قيمة الاهلاك'),
        ),
    ]
