# Generated by Django 4.2 on 2023-07-10 00:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0044_destruction_branch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestructionTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التحويل')),
                ('transfer_title', models.CharField(max_length=100, verbose_name='بيان التحويل')),
                ('asset_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.assetitems', verbose_name='الأصل')),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_destructions', to='add_asset_invoice.branch', verbose_name='الفرع الهدف')),
                ('destruction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.destruction', verbose_name='رقم الاهلاك')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_destructions', to='add_asset_invoice.branch', verbose_name='الفرع المصدر')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التحويل')),
                ('transfer_title', models.CharField(max_length=100, verbose_name='بيان التحويل')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.assetitems', verbose_name='الأصل')),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transfers', to='add_asset_invoice.branch', verbose_name='الفرع الهدف')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transfers', to='add_asset_invoice.branch', verbose_name='الفرع المصدر')),
            ],
        ),
    ]
