# Generated by Django 4.2 on 2023-07-10 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0045_destructiontransfer_assettransfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettransfer',
            old_name='asset',
            new_name='asset_id',
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='destruction_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.destruction', verbose_name='رقم الاهلاك'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DestructionTransfer',
        ),
    ]
