# Generated by Django 4.2 on 2023-07-10 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0046_rename_asset_assettransfer_asset_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettransfer',
            old_name='asset_id',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='assettransfer',
            old_name='destruction_id',
            new_name='destruction',
        ),
    ]
