# Generated by Django 4.2 on 2023-07-13 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0048_alter_assettransfer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assettransfer',
            options={},
        ),
    ]
