# Generated by Django 4.2 on 2023-07-17 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0049_alter_assettransfer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransferDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.assettransfer')),
            ],
        ),
    ]
