# Generated by Django 4.2 on 2023-07-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0050_assettransferdummy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettransferdummy',
            old_name='asset_transfer',
            new_name='transfer_asset',
        ),
        migrations.AddField(
            model_name='assettransferdummy',
            name='transfer_title',
            field=models.CharField(default=1, max_length=100, verbose_name='بيان التحويل'),
            preserve_default=False,
        ),
    ]
