# Generated by Django 4.2 on 2023-07-17 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0052_alter_assettransferdummy_transfer_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransferdummy',
            name='destination_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dummy_destination_transfers', to='add_asset_invoice.branch', verbose_name='الفرع الهدف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assettransferdummy',
            name='source_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dummy_source_transfers', to='add_asset_invoice.branch', verbose_name='الفرع المصدر'),
            preserve_default=False,
        ),
    ]
