# Generated by Django 4.2.2 on 2023-07-17 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0053_assettransferdummy_destination_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferAssetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التحويل')),
                ('transfer_title', models.CharField(max_length=100, verbose_name='بيان التحويل')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.assetitems', verbose_name='الأصل')),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transfers_details', to='add_asset_invoice.branch', verbose_name='الفرع الهدف')),
                ('destruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.destruction', verbose_name='رقم الاهلاك')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transfers_details', to='add_asset_invoice.branch', verbose_name='الفرع المصدر')),
            ],
        ),
        migrations.RenameModel(
            old_name='AssetTransfer',
            new_name='TransferAsset',
        ),
        migrations.DeleteModel(
            name='AssetTransferDummy',
        ),
        migrations.AddField(
            model_name='transferassetdetails',
            name='transfer_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.transferasset', verbose_name='التحويل'),
        ),
    ]
