# Generated by Django 4.2 on 2023-07-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0054_transferassetdetails_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransferAsset',
            new_name='Transfer',
        ),
        migrations.RenameModel(
            old_name='TransferAssetDetails',
            new_name='TransferDestructionDetails',
        ),
    ]
