# Generated by Django 4.2 on 2023-07-17 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0055_rename_transferasset_transfer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferdestructiondetails',
            old_name='transfer_asset',
            new_name='transfer_destruction',
        ),
        migrations.RemoveField(
            model_name='transferdestructiondetails',
            name='transfer_title',
        ),
        migrations.AlterField(
            model_name='transferdestructiondetails',
            name='destination_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transfers_destruction', to='add_asset_invoice.branch', verbose_name='الفرع الهدف'),
        ),
        migrations.AlterField(
            model_name='transferdestructiondetails',
            name='source_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transfers_destruction', to='add_asset_invoice.branch', verbose_name='الفرع المصدر'),
        ),
        migrations.CreateModel(
            name='TransferAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التحويل')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.assetitems', verbose_name='الأصل')),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transfers_asset', to='add_asset_invoice.branch', verbose_name='الفرع الهدف')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transfers_asset', to='add_asset_invoice.branch', verbose_name='الفرع المصدر')),
                ('transfer_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_asset_invoice.transfer', verbose_name='التحويل')),
            ],
        ),
    ]
