# Generated by Django 4.2 on 2023-07-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0056_rename_transfer_asset_transferdestructiondetails_transfer_destruction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='destruction',
        ),
    ]
