# Generated by Django 4.2 on 2023-07-29 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0057_remove_transfer_destruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='source_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_transfers', to='add_asset_invoice.branch', verbose_name='الفرع المصدر'),
        ),
        migrations.AlterField(
            model_name='transferdestructiondetails',
            name='source_branch',
            field=models.ForeignKey(limit_choices_to={'is_source_branch': True}, on_delete=django.db.models.deletion.CASCADE, related_name='source_transfers_destruction', to='add_asset_invoice.branch', verbose_name='الفرع المصدر'),
        ),
    ]
