# Generated by Django 4.2 on 2023-07-29 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0058_alter_transfer_source_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdestructiondetails',
            name='source_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transfers_destruction', to='add_asset_invoice.branch', verbose_name='الفرع المصدر'),
        ),
    ]
