# Generated by Django 4.2 on 2023-07-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0059_alter_transferdestructiondetails_source_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferasset',
            old_name='destination_branch',
            new_name='destination_branch_asset',
        ),
        migrations.RenameField(
            model_name='transferasset',
            old_name='source_branch',
            new_name='source_branch_asset',
        ),
        migrations.RenameField(
            model_name='transferasset',
            old_name='transfer_date',
            new_name='transfer_date_asset',
        ),
        migrations.RenameField(
            model_name='transferdestructiondetails',
            old_name='destination_branch',
            new_name='destination_branch_destruction',
        ),
        migrations.RenameField(
            model_name='transferdestructiondetails',
            old_name='source_branch',
            new_name='source_branch_destruction',
        ),
        migrations.RenameField(
            model_name='transferdestructiondetails',
            old_name='transfer_date',
            new_name='transfer_date_destruction',
        ),
    ]
