# Generated by Django 4.2 on 2023-08-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0060_rename_destination_branch_transferasset_destination_branch_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdestructiondetails',
            name='destruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transfers_key', to='add_asset_invoice.destruction', verbose_name='رقم الاهلاك'),
        ),
    ]
