# Generated by Django 4.2 on 2023-08-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0061_alter_transferdestructiondetails_destruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinvoice',
            name='bank_account_number_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب'),
        ),
        migrations.AddField(
            model_name='assetinvoice',
            name='bank_account_number_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحساب'),
        ),
        migrations.AddField(
            model_name='assetinvoice',
            name='bank_name_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='assetinvoice',
            name='bank_name_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='assetinvoice',
            name='commercial_record',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سجل تجاري'),
        ),
        migrations.AddField(
            model_name='assetinvoice',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الشركة'),
        ),
        migrations.AddField(
            model_name='assetinvoice',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم البطاقة الشخصية'),
        ),
        migrations.AddField(
            model_name='assetinvoice',
            name='tax_card',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='بطاقة ضريبية'),
        ),
    ]
