# Generated by Django 4.2 on 2023-08-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0062_assetinvoice_bank_account_number_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinvoice',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المورد'),
        ),
        migrations.AlterField(
            model_name='assetinvoice',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المحول الية'),
        ),
    ]
