# Generated by Django 4.2.5 on 2023-09-06 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('add_asset_invoice', '0063_alter_assetinvoice_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinvoice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
