# Generated by Django 4.2.5 on 2023-09-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0064_assetinvoice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinvoice',
            name='user',
        ),
    ]
