# Generated by Django 4.2.5 on 2023-09-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0068_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=models.CharField(choices=[('screenViewInvoices', 'شاشة الفواتير'), ('screenViewDestruction', 'شاشة الاهلاك'), ('screenViewTransfer', 'شاشة التحويل')], default='screenViewInvoices', max_length=255, verbose_name='صلاحية الشاشات'),
        ),
    ]
