# Generated by Django 4.2.6 on 2023-10-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_asset_invoice', '0069_alter_userpermission_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=models.CharField(choices=[('screenViewInvoices', 'شاشة الفواتير'), ('screenViewDestruction', 'شاشة الاهلاك'), ('screenViewTransfer', 'شاشة التحويل'), ('screenViewGroup', 'شاشة التصنيف'), ('screenViewPranches', 'شاشة الفروع'), ('screenViewAdditionTax', 'شاشة اضافة ضريبة الزيادة'), ('screenViewMinusTax', 'شاشة اضافة ضريبة الخصم'), ('screenViewCoast', 'شاشة اضافة المصروف'), ('screenViewPermission', 'شاشة اضافة لصلاحيات')], default='screenViewInvoices', max_length=255, verbose_name='صلاحية الشاشات'),
        ),
    ]
